//! The [`Password`] type returned by password generation.

use std::fmt;

/// A generated password.
///
/// The value is deliberately awkward to leak:
///
/// * [`Debug`] prints `Password(<redacted>)`, so a password cannot slip into a
///   log line through a `{:?}` on some enclosing struct.
/// * There is no [`Display`](fmt::Display) implementation. Reading the secret
///   is always explicit, via [`as_str`](Self::as_str) or
///   [`into_string`](Self::into_string).
/// * With the `zeroize` feature (enabled by default), the string buffer is
///   overwritten before the password is dropped, reducing the chance that the
///   secret remains in memory.
///
/// # Examples
/// ```
/// use tayna::PasswordPolicy;
///
/// let policy = PasswordPolicy::builder().length(12).build()?;
/// let password = policy.generate();
///
/// assert_eq!(password.len(), 12);
/// assert_eq!(format!("{password:?}"), "Password(<redacted>)");
/// # Ok::<(), tayna::PolicyError>(())
/// ```
pub struct Password(String);

impl Password {
    /// Wraps an already generated secret.
    pub(crate) fn new(secret: String) -> Self {
        Self(secret)
    }

    /// Borrows the password as a string slice.
    ///
    /// # Examples
    /// ```
    /// use tayna::{CharClass, PasswordPolicy};
    ///
    /// let policy = PasswordPolicy::builder()
    ///     .length(8)
    ///     .classes(CharClass::Digits)
    ///     .build()?;
    ///
    /// assert!(policy.generate().as_str().chars().all(|c| c.is_ascii_digit()));
    /// # Ok::<(), tayna::PolicyError>(())
    /// ```
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consumes the wrapper and returns the underlying [`String`].
    ///
    /// The returned string is no longer wiped on drop. From here on, protecting the
    /// secret is the caller's responsibility.
    ///
    /// # Examples
    /// ```
    /// use tayna::PasswordPolicy;
    ///
    /// let policy = PasswordPolicy::builder().length(16).build()?;
    ///
    /// // Useful when the secret has to be handed to an API that takes an owned
    /// // `String`.
    /// let secret: String = policy.generate().into_string();
    ///
    /// assert_eq!(secret.len(), 16);
    /// # Ok::<(), tayna::PolicyError>(())
    /// ```
    #[must_use]
    pub fn into_string(mut self) -> String {
        // Because `Password` implements `Drop` when the `zeroize` feature is enabled,
        // the inner `String` cannot be moved directly out of `self`. Replacing it with
        // an empty string lets Drop run safely without wiping the returned secret.
        core::mem::take(&mut self.0)
    }

    /// Returns the number of characters in the password.
    ///
    /// This counts Unicode scalar values rather than bytes. Generated passwords
    /// contain only ASCII characters, so for passwords generated by this crate,
    /// this is also the byte length.
    #[must_use]
    pub fn len(&self) -> usize {
        self.0.chars().count()
    }

    /// Returns `true` if the password is empty.
    ///
    /// A password produced by a [`PasswordPolicy`](crate::PasswordPolicy) is never
    /// empty; this exists only for completeness alongside [`len`](Self::len).
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

/// Formats the password without revealing it.
impl fmt::Debug for Password {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Password(<redacted>)")
    }
}

impl AsRef<str> for Password {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl From<Password> for String {
    fn from(password: Password) -> Self {
        password.into_string()
    }
}

/// Overwrites the password's buffer before it is released.
///
/// This is best effort and cannot guarantee that no other copies of the
/// password remain in memory.
#[cfg(feature = "zeroize")]
impl Drop for Password {
    fn drop(&mut self) {
        use zeroize::Zeroize;

        self.0.zeroize();
    }
}

#[cfg(test)]
mod tests {
    use super::Password;

    #[test]
    fn as_str_preserves_the_secret_without_consuming_password() {
        let password = Password::new("123456".to_owned());
        let secret = password.as_str();

        assert_eq!(secret, "123456");
        assert_eq!(password.len(), secret.len());
    }

    #[test]
    fn into_string_preserves_the_secret() {
        let secret = Password::new("abcdef".to_owned()).into_string();

        assert_eq!(secret, "abcdef");
    }

    #[test]
    fn len_returns_character_count() {
        let password = Password::new("é".to_owned());
        let other_password = Password::new("xyz".to_owned());

        assert_eq!(password.len(), 1);
        assert_eq!(other_password.len(), 3);
    }

    #[test]
    fn empty_password_reports_zero_length_and_is_empty() {
        let password = Password::new(String::new());

        assert_eq!(password.len(), 0);
        assert!(password.is_empty());
        assert_eq!(password.as_str(), "");
    }

    #[test]
    fn debug_does_not_reveal_the_secret() {
        let password = Password::new("hunter2!".to_owned());
        let rendered = format!("{password:?}");

        assert_eq!(rendered, "Password(<redacted>)");
        assert!(!rendered.contains("hunter2"));
    }

    #[test]
    fn as_ref_str_for_password_preserves_the_secret() {
        let other_password = Password::new("123456".to_owned());
        let other_secret = other_password.as_ref();

        assert_eq!(other_secret, "123456");
    }

    #[test]
    fn from_password_for_string_preserves_the_secret() {
        let password = Password::new("abcdef".to_owned());
        let secret = String::from(password);

        let other_password = Password::new("secret".to_owned());
        let other_secret: String = other_password.into();

        assert_eq!(secret, "abcdef");
        assert_eq!(other_secret, "secret");
    }
}
